### ISSUE TITLE
Pug bug

### ISSUE THREAD

**Issue by Grawl** [rajdee/posthtml-bem#17]
Don't know how it was broken but it's really annoying.

I use PostHTML after [Pug](http://pugjs.org) in [Gulp](http://gulpjs.com):

``` js
.pipe($.pug())
.pipe($.posthtml())
```

Looks like Pug should make some HTML and PostHTML should process it **after** pug. But it doesn't. If I use `elem` attribute into Pug mixin, it's ignored by PostHTML and remains as is.
### Expected behaviour

Input:

``` pug
extends views/layout
block content
    main(block='foo')
        header(elem='bar')
        mixin item
            li(elem='baz') item
        ul
            +item
            +item
            +item
```

Output:

``` html
…
    <main class="foo">
      <header class="foo-bar"></header>
      <ul>
              <li class="foo-baz">item</li>
              <li class ="foo-baz">item</li>
              <li class ="foo-baz">item</li>
      </ul>
    </main>
…
```
### Unexpected output

``` html
…
    <main class="foo">
      <header class="foo-bar"></header>
      <ul>
              <li elem="baz">item</li>
              <li elem="baz">item</li>
              <li elem="baz">item</li>
      </ul>
    </main>
…
```

I created a repository for this bug: https://github.com/Grawl/posthtml-bem-pug-bug

**Comment by rajdee** [comment]
Hi @Grawl 
The problem is that **_li elem='baz'**_ isn't a child of the **_main(block='foo')**_ element. It's a child of **_ul**_. If you add a **_block='foo'**_ in mixin item, it will be work

``` js
        mixin item
            li(block='foo' elem='baz') item
```

I think it can be considered a bug, but it's more complex issue than it may seem

**Comment by Grawl** [comment]
@rajdee oh the problem was too simple. Maybe we have to mention this limitation in project readme? And it will be good to get rid of it.
