### ISSUE TITLE
Error message when using posthtml-bem in Twig templates

### ISSUE THREAD

**Issue by almai** [rajdee/posthtml-bem#19]
When I try to do sth like this...

`<body {{ post_classes }}>`

in a Timber template and the posthtml-bem plugin is activated I get the following error:

`Fatal error: Uncaught Twig_Error_Syntax: Unclosed "variable". in /var/www/html/wp-content/themes/fdk/views/base.twig on line 11`

It turns out that posthtml-bem tries to interprete everything in between braces as key-value-pairs and then throws an error.

Two variations of this error where reported [here](https://github.com/fabrica-wp/fabrica-dev-kit/issues/14) and [here](https://github.com/timber/timber/issues/1512#issuecomment-320937965).

**Comment by almai** [comment]
Is this project still alive?

**Comment by voischev** [comment]
@Scrum see

**Comment by Scrum** [comment]
@almai Hello, is this still relevant for you?

**Comment by almai** [comment]
Yes, please fix!!

After 5 yrs? No! 😂
