### ISSUE TITLE
Mention BEML

### ISSUE THREAD

**Issue by pepelsbey** [rajdee/posthtml-bem#6]
It seems this plugin is heavily inspired by @zenwalker’s [BEML](https://github.com/zenwalker/node-beml). Well at least @rajdee was [totally aware](https://github.com/zenwalker/node-beml/commit/7df3001521f68b83fac352e0d9012aa571d65300) of its existence. So it would be good to mention original project in form of “inspired by” or “based on”.

**Comment by rajdee** [comment]
Of course I know about the existence of BEML and bemto. I wanted to add the functionality, but then decided it was easier to write own plugin. The functionality in the end I decided to move to a separate plugin :)
I'm not against these sources of inspiration, but I have to choose which one of them

**Comment by rajdee** [comment]
[It was done](https://github.com/rajdee/posthtml-bem#predecessors)

**Comment by pepelsbey** [comment]
Thank you! It’s always good to thank people and projects that inspired you.
